In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("telecom_customer.csv")

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
print(df.columns
     )

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [6]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [7]:
df = df.drop(["customerID"], axis=1)

In [8]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [9]:
df = pd.get_dummies(df,columns=["gender"])

In [10]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male
0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False
1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,False,True
2,0,No,No,2,Yes,No,DSL,Yes,Yes,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True
3,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True
4,0,No,No,2,Yes,No,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,True
7039,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False
7040,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False
7041,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,False,True
7042,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True

In [11]:
df["Partner"] = df["Partner"].map({
     "Yes": 1,
     "No":0

})

In [12]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male
0,0,1,No,1,No,No phone service,DSL,No,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False
1,0,0,No,34,Yes,No,DSL,Yes,No,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,False,True
2,0,0,No,2,Yes,No,DSL,Yes,Yes,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True
3,0,0,No,45,No,No phone service,DSL,Yes,No,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True
4,0,0,No,2,Yes,No,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,Yes,24,Yes,Yes,DSL,Yes,No,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,True
7039,0,1,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False
7040,0,1,Yes,11,No,No phone service,DSL,Yes,No,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False
7041,1,1,No,4,Yes,Yes,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,False,True
7042,0,0,No,66,Yes,No,Fiber optic,Yes,No,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True

In [13]:
df["Dependents"] = df["Dependents"].map({
     "Yes": 1,
     "No":0

})

In [14]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male
0,0,1,0,1,No,No phone service,DSL,No,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False
1,0,0,0,34,Yes,No,DSL,Yes,No,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,False,True
2,0,0,0,2,Yes,No,DSL,Yes,Yes,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True
3,0,0,0,45,No,No phone service,DSL,Yes,No,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True
4,0,0,0,2,Yes,No,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,24,Yes,Yes,DSL,Yes,No,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,True
7039,0,1,1,72,Yes,Yes,Fiber optic,No,Yes,Yes,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False
7040,0,1,1,11,No,No phone service,DSL,Yes,No,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False
7041,1,1,0,4,Yes,Yes,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,False,True
7042,0,0,0,66,Yes,No,Fiber optic,Yes,No,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True

In [15]:
tenure_max = df["tenure"].min()
tenure_min = df["tenure"].max()

In [16]:
df["tenure"] = (df["tenure"] - tenure_min)/(tenure_max - tenure_min)

In [17]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male
0,0,1,0,0.986111,No,No phone service,DSL,No,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False
1,0,0,0,0.527778,Yes,No,DSL,Yes,No,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,False,True
2,0,0,0,0.972222,Yes,No,DSL,Yes,Yes,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True
3,0,0,0,0.375000,No,No phone service,DSL,Yes,No,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True
4,0,0,0,0.972222,Yes,No,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,Yes,Yes,DSL,Yes,No,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,True
7039,0,1,1,-0.000000,Yes,Yes,Fiber optic,No,Yes,Yes,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False
7040,0,1,1,0.847222,No,No phone service,DSL,Yes,No,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False
7041,1,1,0,0.944444,Yes,Yes,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,False,True
7042,0,0,0,0.083333,Yes,No,Fiber optic,Yes,No,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True

In [18]:
df["PhoneService"] = df["PhoneService"].map({
     "Yes": 1,
     "No":0

})

In [19]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male
0,0,1,0,0.986111,0,No phone service,DSL,No,Yes,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False
1,0,0,0,0.527778,1,No,DSL,Yes,No,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,False,True
2,0,0,0,0.972222,1,No,DSL,Yes,Yes,No,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True
3,0,0,0,0.375000,0,No phone service,DSL,Yes,No,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True
4,0,0,0,0.972222,1,No,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,Yes,DSL,Yes,No,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,True
7039,0,1,1,-0.000000,1,Yes,Fiber optic,No,Yes,Yes,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False
7040,0,1,1,0.847222,0,No phone service,DSL,Yes,No,No,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False
7041,1,1,0,0.944444,1,Yes,Fiber optic,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,False,True
7042,0,0,0,0.083333,1,No,Fiber optic,Yes,No,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True

In [20]:
df["MultipleLines"].unique()

<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

In [21]:
df = pd.get_dummies(df, columns=["MultipleLines"])

In [22]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes
0,0,1,0,0.986111,0,DSL,No,Yes,No,No,...,Yes,Electronic check,29.85,29.85,No,True,False,False,True,False
1,0,0,0,0.527778,1,DSL,Yes,No,Yes,No,...,No,Mailed check,56.95,1889.5,No,False,True,True,False,False
2,0,0,0,0.972222,1,DSL,Yes,Yes,No,No,...,Yes,Mailed check,53.85,108.15,Yes,False,True,True,False,False
3,0,0,0,0.375000,0,DSL,Yes,No,Yes,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,False,True,False,True,False
4,0,0,0,0.972222,1,Fiber optic,No,No,No,No,...,Yes,Electronic check,70.70,151.65,Yes,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,DSL,Yes,No,Yes,Yes,...,Yes,Mailed check,84.80,1990.5,No,False,True,False,False,True
7039,0,1,1,-0.000000,1,Fiber optic,No,Yes,Yes,No,...,Yes,Credit card (automatic),103.20,7362.9,No,True,False,False,False,True
7040,0,1,1,0.847222,0,DSL,Yes,No,No,No,...,Yes,Electronic check,29.60,346.45,No,True,False,False,True,False
7041,1,1,0,0.944444,1,Fiber optic,No,No,No,No,...,Yes,Mailed check,74.40,306.6,Yes,False,True,False,False,True
7042,0,0,0,0.083333,1,Fiber optic,Yes,No,Yes,Yes,...,Yes,Bank transfer (automatic),105.65,6844.5,No,False,True,True,False,False

In [23]:
df["InternetService"].unique()

<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

In [24]:
df = pd.get_dummies(df, columns=["InternetService"])

In [25]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No
0,0,1,0,0.986111,0,No,Yes,No,No,No,...,29.85,No,True,False,False,True,False,True,False,False
1,0,0,0,0.527778,1,Yes,No,Yes,No,No,...,1889.5,No,False,True,True,False,False,True,False,False
2,0,0,0,0.972222,1,Yes,Yes,No,No,No,...,108.15,Yes,False,True,True,False,False,True,False,False
3,0,0,0,0.375000,0,Yes,No,Yes,Yes,No,...,1840.75,No,False,True,False,True,False,True,False,False
4,0,0,0,0.972222,1,No,No,No,No,No,...,151.65,Yes,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,Yes,No,Yes,Yes,Yes,...,1990.5,No,False,True,False,False,True,True,False,False
7039,0,1,1,-0.000000,1,No,Yes,Yes,No,Yes,...,7362.9,No,True,False,False,False,True,False,True,False
7040,0,1,1,0.847222,0,Yes,No,No,No,No,...,346.45,No,True,False,False,True,False,True,False,False
7041,1,1,0,0.944444,1,No,No,No,No,No,...,306.6,Yes,False,True,False,False,True,False,True,False
7042,0,0,0,0.083333,1,Yes,No,Yes,Yes,Yes,...,6844.5,No,False,True,True,False,False,False,True,False

In [26]:
df["OnlineSecurity"] = df["OnlineSecurity"].map({
    "No":0,
    "Yes":1
})

In [27]:
df["OnlineBackup"] = df["OnlineBackup"].map({
    "No":0,
    "Yes":1
})

In [28]:
df["DeviceProtection"] = df["DeviceProtection"].map({
    "No":0,
    "Yes":1
})

In [29]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No
0,0,1,0,0.986111,0,0.0,1.0,0.0,No,No,...,29.85,No,True,False,False,True,False,True,False,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,No,No,...,1889.5,No,False,True,True,False,False,True,False,False
2,0,0,0,0.972222,1,1.0,1.0,0.0,No,No,...,108.15,Yes,False,True,True,False,False,True,False,False
3,0,0,0,0.375000,0,1.0,0.0,1.0,Yes,No,...,1840.75,No,False,True,False,True,False,True,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,No,No,...,151.65,Yes,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,Yes,Yes,...,1990.5,No,False,True,False,False,True,True,False,False
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,No,Yes,...,7362.9,No,True,False,False,False,True,False,True,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,No,No,...,346.45,No,True,False,False,True,False,True,False,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,No,No,...,306.6,Yes,False,True,False,False,True,False,True,False
7042,0,0,0,0.083333,1,1.0,0.0,1.0,Yes,Yes,...,6844.5,No,False,True,True,False,False,False,True,False

In [30]:
df.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Female', 'gender_Male', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No'],
      dtype='str')

In [31]:
print(df.dtypes)

SeniorCitizen                       int64
Partner                             int64
Dependents                          int64
tenure                            float64
PhoneService                        int64
OnlineSecurity                    float64
OnlineBackup                      float64
DeviceProtection                  float64
TechSupport                           str
StreamingTV                           str
StreamingMovies                       str
Contract                              str
PaperlessBilling                      str
PaymentMethod                         str
MonthlyCharges                    float64
TotalCharges                          str
Churn                                 str
gender_Female                        bool
gender_Male                          bool
MultipleLines_No                     bool
MultipleLines_No phone service       bool
MultipleLines_Yes                    bool
InternetService_DSL                  bool
InternetService_Fiber optic          bool
InternetService_No                   bool
dtype: object

In [32]:
binary_cols = ["TechSupport", "StreamingTV", "PaperlessBilling", "StreamingMovies"]
for i in binary_cols:
    df[i] = df[i].map({
        "No":0,
        "Yes":1
    })

In [33]:
print(df.dtypes)

SeniorCitizen                       int64
Partner                             int64
Dependents                          int64
tenure                            float64
PhoneService                        int64
OnlineSecurity                    float64
OnlineBackup                      float64
DeviceProtection                  float64
TechSupport                       float64
StreamingTV                       float64
StreamingMovies                   float64
Contract                              str
PaperlessBilling                    int64
PaymentMethod                         str
MonthlyCharges                    float64
TotalCharges                          str
Churn                                 str
gender_Female                        bool
gender_Male                          bool
MultipleLines_No                     bool
MultipleLines_No phone service       bool
MultipleLines_Yes                    bool
InternetService_DSL                  bool
InternetService_Fiber optic          bool
InternetService_No                   bool
dtype: object

In [34]:
df["PaymentMethod"].unique()

<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [35]:
df = pd.get_dummies(df, columns=["Contract","PaymentMethod"])

In [36]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,...,True,False,False,False,True,False,False,False,False,True
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,False,True
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,...,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,...,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,...,True,False,False,False,True,False,False,False,False,True
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,...,False,True,False,False,True,False,False,True,False,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,...,False,True,False,True,False,False,False,False,False,True
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,...,False,True,False,False,False,True,True,False,False,False

In [37]:
df[["MonthlyCharges", "TotalCharges"]]

      MonthlyCharges TotalCharges
0              29.85        29.85
1              56.95       1889.5
2              53.85       108.15
3              42.30      1840.75
4              70.70       151.65
...              ...          ...
7038           84.80       1990.5
7039          103.20       7362.9
7040           29.60       346.45
7041           74.40        306.6
7042          105.65       6844.5

[7043 rows x 2 columns]

In [38]:
df = df[df['TotalCharges'].str.strip() != '']

In [39]:
import numpy as np
df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

In [40]:
min_MC = df["MonthlyCharges"].min()
max_MC = df["MonthlyCharges"].max()
min_TC = float(df["TotalCharges"].min())
max_TC = float(df["TotalCharges"].max())
print(f" min MC = {min_MC} max MC = {max_MC} min_TC ={ min_TC} max TC = { max_TC}")

 min MC = 18.25 max MC = 118.75 min_TC =18.8 max TC = 8684.8

In [41]:
df["TotalCharges"].min()

np.float64(18.8)

In [42]:
df["MonthlyCharges"] = (df["MonthlyCharges"]-min_MC)/(max_MC - min_MC)

In [43]:
df.dropna(inplace=True)

In [44]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,...,True,False,False,False,True,False,False,False,False,True
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,False,True
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,...,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,...,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,...,True,False,False,False,True,False,False,False,False,True
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,...,False,True,False,False,True,False,False,True,False,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,...,False,True,False,True,False,False,False,False,False,True
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,...,False,True,False,False,False,True,True,False,False,False

In [45]:
print(df.dtypes)

SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
tenure                                     float64
PhoneService                                 int64
OnlineSecurity                             float64
OnlineBackup                               float64
DeviceProtection                           float64
TechSupport                                float64
StreamingTV                                float64
StreamingMovies                            float64
PaperlessBilling                             int64
MonthlyCharges                             float64
TotalCharges                               float64
Churn                                          str
gender_Female                                 bool
gender_Male                                   bool
MultipleLines_No                              bool
MultipleLines_No phone service                bool
MultipleLines_Yes                             bool
InternetService_DSL                           bool
InternetService_Fiber optic                   bool
InternetService_No                            bool
Contract_Month-to-month                       bool
Contract_One year                             bool
Contract_Two year                             bool
PaymentMethod_Bank transfer (automatic)       bool
PaymentMethod_Credit card (automatic)         bool
PaymentMethod_Electronic check                bool
PaymentMethod_Mailed check                    bool
dtype: object

In [46]:
pd.set_option('display.max_columns', None)

In [47]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,0.0,1,0.115423,29.85,No,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,0.0,0,0.385075,1889.50,No,False,True,True,False,False,True,False,False,False,True,False,False,False,False,True
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,0.0,1,0.354229,108.15,Yes,False,True,True,False,False,True,False,False,True,False,False,False,False,False,True
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,0.0,0,0.239303,1840.75,No,False,True,False,True,False,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.521891,151.65,Yes,True,False,True,False,False,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.662189,1990.50,No,False,True,False,False,True,True,False,False,False,True,False,False,False,False,True
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,1.0,1,0.845274,7362.90,No,True,False,False,False,True,False,True,False,False,True,False,False,True,False,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,0.0,1,0.112935,346.45,No,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.558706,306.60,Yes,False,True,False,False,True,False,True,False,True,False,False,False,False,False,True
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.869652,6844.50,No,False,True,True,False,False,False,True,False,False,False,True,True,False,False,False

In [48]:
df["TotalCharges"] = (df["TotalCharges"]-min_TC)/(max_TC - min_TC)

In [49]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,0.0,1,0.115423,0.001275,No,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,0.0,0,0.385075,0.215867,No,False,True,True,False,False,True,False,False,False,True,False,False,False,False,True
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,0.0,1,0.354229,0.010310,Yes,False,True,True,False,False,True,False,False,True,False,False,False,False,False,True
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,0.0,0,0.239303,0.210241,No,False,True,False,True,False,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.521891,0.015330,Yes,True,False,True,False,False,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.662189,0.227521,No,False,True,False,False,True,True,False,False,False,True,False,False,False,False,True
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,1.0,1,0.845274,0.847461,No,True,False,False,False,True,False,True,False,False,True,False,False,True,False,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,0.0,1,0.112935,0.037809,No,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.558706,0.033210,Yes,False,True,False,False,True,False,True,False,True,False,False,False,False,False,True
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.869652,0.787641,No,False,True,True,False,False,False,True,False,False,False,True,True,False,False,False

In [50]:
df1 = df.copy()

In [51]:
df["Churn"] = df["Churn"].map({
    'No':0,
    'Yes':1
})

In [52]:
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,0.0,1,0.115423,0.001275,0,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,0.0,0,0.385075,0.215867,0,False,True,True,False,False,True,False,False,False,True,False,False,False,False,True
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,0.0,1,0.354229,0.010310,1,False,True,True,False,False,True,False,False,True,False,False,False,False,False,True
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,0.0,0,0.239303,0.210241,0,False,True,False,True,False,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.521891,0.015330,1,True,False,True,False,False,False,True,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.662189,0.227521,0,False,True,False,False,True,True,False,False,False,True,False,False,False,False,True
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,1.0,1,0.845274,0.847461,0,True,False,False,False,True,False,True,False,False,True,False,False,True,False,False
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,0.0,1,0.112935,0.037809,0,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.558706,0.033210,1,False,True,False,False,True,False,True,False,True,False,False,False,False,False,True
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.869652,0.787641,0,False,True,True,False,False,False,True,False,False,False,True,True,False,False,False

In [53]:
y = df["Churn"]

In [54]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 5512, dtype: int64

In [55]:
x = df.drop(["Churn"], axis=1)

In [56]:
x["ServicesUsed"] = df["PhoneService"] + df["OnlineSecurity"] + df["OnlineBackup"] + df["TechSupport"] + df["StreamingTV"] + df["StreamingMovies"]

In [57]:
print(x.columns)

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'gender_Female', 'gender_Male', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'ServicesUsed'],
      dtype='str')

In [58]:
x["ServicesUsed"].max()

np.float64(6.0)

In [59]:
x["HeavyUser"] = (
    x["ServicesUsed"] >= 3
).astype(int)

In [60]:
x

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,gender_Female,gender_Male,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,ServicesUsed,HeavyUser
0,0,1,0,0.986111,0,0.0,1.0,0.0,0.0,0.0,0.0,1,0.115423,0.001275,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False,1.0,0
1,0,0,0,0.527778,1,1.0,0.0,1.0,0.0,0.0,0.0,0,0.385075,0.215867,False,True,True,False,False,True,False,False,False,True,False,False,False,False,True,2.0,0
2,0,0,0,0.972222,1,1.0,1.0,0.0,0.0,0.0,0.0,1,0.354229,0.010310,False,True,True,False,False,True,False,False,True,False,False,False,False,False,True,3.0,1
3,0,0,0,0.375000,0,1.0,0.0,1.0,1.0,0.0,0.0,0,0.239303,0.210241,False,True,False,True,False,True,False,False,False,True,False,True,False,False,False,2.0,0
4,0,0,0,0.972222,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.521891,0.015330,True,False,True,False,False,False,True,False,True,False,False,False,False,True,False,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,0.666667,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.662189,0.227521,False,True,False,False,True,True,False,False,False,True,False,False,False,False,True,5.0,1
7039,0,1,1,-0.000000,1,0.0,1.0,1.0,0.0,1.0,1.0,1,0.845274,0.847461,True,False,False,False,True,False,True,False,False,True,False,False,True,False,False,4.0,1
7040,0,1,1,0.847222,0,1.0,0.0,0.0,0.0,0.0,0.0,1,0.112935,0.037809,True,False,False,True,False,True,False,False,True,False,False,False,False,True,False,1.0,0
7041,1,1,0,0.944444,1,0.0,0.0,0.0,0.0,0.0,0.0,1,0.558706,0.033210,False,True,False,False,True,False,True,False,True,False,False,False,False,False,True,1.0,0
7042,0,0,0,0.083333,1,1.0,0.0,1.0,1.0,1.0,1.0,1,0.869652,0.787641,False,True,True,False,False,False,True,False,False,False,True,True,False,False,False,5.0,1

In [61]:
print(x.columns)

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'gender_Female', 'gender_Male', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'ServicesUsed', 'HeavyUser'],
      dtype='str')

In [73]:
from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier

In [74]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2, random_state = 42)

In [81]:
# model = RandomForestClassifier(
#     n_estimators=500,
#     max_depth = 10,
#     min_samples_split=5,
#     random_state=42
# )

In [88]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

In [89]:
model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [90]:
model.score(x_test,y_test)

0.7552130553037172

In [91]:
df.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'Churn', 'gender_Female', 'gender_Male',
       'MultipleLines_No', 'MultipleLines_No phone service',
       'MultipleLines_Yes', 'InternetService_DSL',
       'InternetService_Fiber optic', 'InternetService_No',
       'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [92]:
import pandas as pd

# ==========================================
# CREATE INPUT DICTIONARY
# ==========================================

input_data = dict.fromkeys(x.columns, 0)

# ==========================================
# NUMERICAL INPUTS
# ==========================================

# tenure
tenure = float(input("Enter Tenure (0-72 months): "))

input_data['tenure'] = tenure / 72

# ------------------------------------------

# MonthlyCharges
# Min = 18.25
# Max = 118.75

monthly = float(input("Enter Monthly Charges: "))

input_data['MonthlyCharges'] = (
    (monthly - 18.25) /
    (118.75 - 18.25)
)

# ------------------------------------------

# TotalCharges
# Min = 18.8
# Max = 8684.8

total = float(input("Enter Total Charges: "))

input_data['TotalCharges'] = (
    (total - 18.8) /
    (8684.8 - 18.8)
)

# ==========================================
# BINARY INPUTS
# ==========================================

binary_cols = [
    'SeniorCitizen',
    'Partner',
    'Dependents',
    'PhoneService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'PaperlessBilling'
]

for col in binary_cols:

    value = int(
        input(f"{col} (0=No, 1=Yes): ")
    )

    input_data[col] = value

# ==========================================
# GENDER
# ==========================================

print("""
Gender:
1 = Male
2 = Female
""")

gender = int(input("Enter Gender: "))

if gender == 1:
    input_data['gender_Male'] = 1

elif gender == 2:
    input_data['gender_Female'] = 1

# ==========================================
# MULTIPLE LINES
# ==========================================

print("""
Multiple Lines:
1 = No
2 = No phone service
3 = Yes
""")

multiple = int(input("Enter Multiple Lines Option: "))

if multiple == 1:
    input_data['MultipleLines_No'] = 1

elif multiple == 2:
    input_data['MultipleLines_No phone service'] = 1

elif multiple == 3:
    input_data['MultipleLines_Yes'] = 1

# ==========================================
# INTERNET SERVICE
# ==========================================

print("""
Internet Service:
1 = DSL
2 = Fiber optic
3 = No
""")

internet = int(input("Enter Internet Service: "))

if internet == 1:
    input_data['InternetService_DSL'] = 1

elif internet == 2:
    input_data['InternetService_Fiber optic'] = 1

elif internet == 3:
    input_data['InternetService_No'] = 1

# ==========================================
# CONTRACT
# ==========================================

print("""
Contract:
1 = Month-to-month
2 = One year
3 = Two year
""")

contract = int(input("Enter Contract Type: "))

if contract == 1:
    input_data['Contract_Month-to-month'] = 1

elif contract == 2:
    input_data['Contract_One year'] = 1

elif contract == 3:
    input_data['Contract_Two year'] = 1

# ==========================================
# PAYMENT METHOD
# ==========================================

print("""
Payment Method:
1 = Bank transfer (automatic)
2 = Credit card (automatic)
3 = Electronic check
4 = Mailed check
""")

payment = int(input("Enter Payment Method: "))

if payment == 1:
    input_data[
        'PaymentMethod_Bank transfer (automatic)'
    ] = 1

elif payment == 2:
    input_data[
        'PaymentMethod_Credit card (automatic)'
    ] = 1

elif payment == 3:
    input_data[
        'PaymentMethod_Electronic check'
    ] = 1

elif payment == 4:
    input_data[
        'PaymentMethod_Mailed check'
    ] = 1

# ==========================================
# FEATURE ENGINEERING
# ==========================================

services_used = (
    input_data['PhoneService'] +
    input_data['OnlineSecurity'] +
    input_data['OnlineBackup'] +
    input_data['DeviceProtection'] +
    input_data['TechSupport'] +
    input_data['StreamingTV'] +
    input_data['StreamingMovies']
)

# Total Services Used
input_data['ServicesUsed'] = services_used

# Heavy User Feature
input_data['HeavyUser'] = (
    1 if services_used >= 3 else 0
)

# ==========================================
# CONVERT TO DATAFRAME
# ==========================================

input_df = pd.DataFrame([input_data])

# ==========================================
# PREDICT PROBABILITY
# ==========================================

prob = model.predict_proba(input_df)

churn_prob = float(prob[0][1]) * 100

# ==========================================
# DISPLAY RESULT
# ==========================================

print(f"\nServices Used: {services_used}")

print(f"Heavy User: {input_data['HeavyUser']}")

print(f"\nChurn Probability: {churn_prob:.2f}%")

# ==========================================
# RISK ANALYSIS
# ==========================================

if churn_prob >= 70:
    print("Customer Will Churn")

elif churn_prob >= 30:
    print("Customer Needs Intervention")

else:
    print("Customer Will Stay")

Enter Tenure (0-72 months):  1
Enter Monthly Charges:  118
Enter Total Charges:  118
SeniorCitizen (0=No, 1=Yes):  1
Partner (0=No, 1=Yes):  0
Dependents (0=No, 1=Yes):  0
PhoneService (0=No, 1=Yes):  1
OnlineSecurity (0=No, 1=Yes):  0
OnlineBackup (0=No, 1=Yes):  0
DeviceProtection (0=No, 1=Yes):  0
TechSupport (0=No, 1=Yes):  0
StreamingTV (0=No, 1=Yes):  0
StreamingMovies (0=No, 1=Yes):  0
PaperlessBilling (0=No, 1=Yes):  1

Gender:
1 = Male
2 = Female

Enter Gender:  2

Multiple Lines:
1 = No
2 = No phone service
3 = Yes

Enter Multiple Lines Option:  3

Internet Service:
1 = DSL
2 = Fiber optic
3 = No

Enter Internet Service:  2

Contract:
1 = Month-to-month
2 = One year
3 = Two year

Enter Contract Type:  1

Payment Method:
1 = Bank transfer (automatic)
2 = Credit card (automatic)
3 = Electronic check
4 = Mailed check

Enter Payment Method:  3

Services Used: 1
Heavy User: 0

Churn Probability: 70.30%
Customer Will Churn

In [93]:
print(df['Churn'].value_counts())

Churn
0    3756
1    1756
Name: count, dtype: int64

In [94]:
prob = model.predict_proba(input_df)

print(prob)

[[0.2969607 0.7030393]]

In [95]:
from sklearn.metrics import classification_report

pred = model.predict(x_test)

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.82       746
           1       0.64      0.55      0.59       357

    accuracy                           0.76      1103
   macro avg       0.72      0.70      0.71      1103
weighted avg       0.75      0.76      0.75      1103

In [96]:
import joblib

In [100]:
joblib.dump(model, "churning_customer.pkl")

['churning_customer.pkl']